import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.linkedin.com/');
  await page.getByRole('link', { name: 'Sign in', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email or phone' }).click();
  await page.getByRole('textbox', { name: 'Email or phone' }).fill('anand.abhishekcorponizers@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('6591@Kiit');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('link', { name: 'Jobs, 0 new notifications' }).click();
  await page.getByRole('link', { name: 'Show all top job picks for you' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container').first().click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Easy Apply to Software' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Three.js?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Three.js?*' }).fill('11');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with WebGL?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Three.js?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Three.js?*' }).fill('1');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with WebGL?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with WebGL?*' }).fill('1');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('#radio-button-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-4433340180-33593232722-multipleChoice').getByText('Yes').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Any prior experience in 3D/').selectOption('Yes');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Submit application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Dismiss' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container').first().click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container.relative.job-card-list.job-card-container--clickable.job-card-list--underline-title-on-hover.jobs-search-two-pane__job-card-container--viewport-tracking-1').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Easy Apply to Backend' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('combobox', { name: 'Location (city) *' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('combobox', { name: 'Location (city) *' }).fill('B');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.search-typeahead-v2__hit').first().click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).fill('450000');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your expected' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your expected' }).fill('60000');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Please select your total years of professional experience:Please select your').selectOption('1 year');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Please select your total additional months of experience:Please select your').selectOption('0 month');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Submit application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Dismiss' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container.relative.job-card-list.job-card-container--clickable.job-card-list--underline-title-on-hover.jobs-search-two-pane__job-card-container--viewport-tracking-3').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('link', { name: 'Apply to Backend Engineer on' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('link', { name: 'Continue to apply to Backend' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('button', { name: 'Apply Now' }).click();
  await page1.locator('.fixed.inset-0').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container.relative.job-card-list.job-card-container--clickable.job-card-list--underline-title-on-hover.jobs-search-two-pane__job-card-container--viewport-tracking-4').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('link', { name: 'Easy Apply' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Easy Apply to Full Stack' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Angular or Reactjs?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How many years of work experience do you have with Angular or Reactjs?*' }).fill('1');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Are you serving notice period').selectOption('Yes');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Submit application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Dismiss' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container.relative.job-card-list.job-card-container--clickable.job-card-list--underline-title-on-hover.jobs-search-two-pane__job-card-container--viewport-tracking-1').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Easy Apply to SDE-I (Backend' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).fill('200000');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your expected' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your current ctc' }).fill('400000');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your expected' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Please enter your expected' }).fill('500000');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Please select your total years of professional experience:Please select your').selectOption('1 year');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByLabel('Please select your total additional months of experience:Please select your').selectOption('0 month');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How soon can you join us?*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'How soon can you join us?*' }).fill('immedaite');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Linkedin Profile*' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Linkedin Profile*' }).fill('aabhisheek');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Share the most impressive' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Share the most impressive' }).fill('linkedinautonomousBot');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('textbox', { name: 'Links to your personal' }).fill('github:aabhisheek');
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Submit application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Dismiss' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.display-flex.job-card-container.relative.job-card-list.job-card-container--clickable.job-card-list--underline-title-on-hover.jobs-search-two-pane__job-card-container--viewport-tracking-2').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('#ember1372').getByText('Bengaluru, Karnataka, India (').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('#ember1381').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().locator('.jobs-details__main-content').click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Easy Apply to Smart TV App' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Review your application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Submit application' }).click();
  await page.locator('[data-testid="interop-iframe"]').contentFrame().getByRole('button', { name: 'Dismiss' }).click();
});